name: Deploy to ECR

# Trigger this workflow after the "Build CI" workflow completes
on:
  workflow_run:
    workflows: ["Build CI"]  # The name of your build workflow
    types:
      - completed

jobs:
  build:
    name: Build and Deploy to ECR
    runs-on: ubuntu-latest

    steps:

      # Checkout the latest code
      - name: Check out code
        uses: actions/checkout@v2

      # Configure AWS credentials to allow GitHub Actions to interact with ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push the Docker image to ECR
      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/rameelhashmi/couponmanagement:latest
            ${{ steps.login-ecr.outputs.registry }}/rameelhashmi/couponmanagement:${{ github.sha }}